{{- if not .Values.cloudflare.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "..fullname" . }}-credentials
  labels:
    {{- include "..labels" . | nindent 4 }}
type: Opaque
stringData:
  tunnelToken: {{ .Values.cloudflare.tunnel_token }}
{{- end }}