name: Release Charts

on:
  push:
    branches:
      - main

jobs:
  release:
    # depending on default permission settings for your org (contents being read-only or read-write for workloads), you will have to add permissions
    # see: https://docs.github.com/en/actions/security-guides/automatic-token-authentication#modifying-the-permissions-for-the-github_token
    permissions:
      contents: write
      packages: write
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@1a275c3b69536ee54be43f2070a358922e12c8d4 # v4.3.1
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@cae68fefc6b5f367a0275617c9f83181ba54714f # v1.7.0
        with:
          skip_existing: true
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: '22.x'
      
      - name: Install OIDC Client from Core Package
        run: npm install @actions/core@1.11.1

      - name: Trigger Helm Chart Sync
        uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # v8.0.0
        with:
          script: |
            const gh_core = require('@actions/core')
            let id_token = await gh_core.getIDToken()
            const response = await fetch('https://github-oidc-worker.cyberjake.xyz/api/v1/workflow', {
              method: 'POST',
              headers: {
                Authorization: `${id_token}`,
                "User-Agent": "Cyb3r-Jak3/helm-cloudflared",
              },
              body: JSON.stringify({
                targetRepo: 'Cyb3r-Jak3/helm-repo',
                targetWorkflow: 'get-charts.yml'
              })
            })
            if (!response.ok) {
              throw new Error(`HTTP error! status: ${response.status}`);
            }
